[tool.semantic_release]
version_variables= ["doodle_django/__init__.py:__version__"]

[tool.semantic_release.commit_parser_options]
allowed_tags = ["ci", "feat", "fix", "refactor", "test"]

[tool.semantic_release.branches."ci-cd-test"]
match = "ci-cd"
prerelease = true
prerelease_token = "rc"