__version__ = "0.1.0-alpha.2"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:__version__"
]

[tool.semantic_release.commit_parser_options]
allowed_tags = ["ci", "feat", "fix", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix"]

[tool.semantic_release.branches.main]
match = "(group_1)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.branches.test]
match = "ci_cd_test"
prerelease = true
prerelease_token = "alpha"