# Generated by Django 4.2.7 on 2023-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.CharField(blank=True, db_column='description', max_length=500, null=True)),
                ('location', models.CharField(blank=True, db_column='location', max_length=100, null=True)),
                ('video_conferencing', models.BooleanField(db_column='video_conferencing')),
                ('duration', models.DurationField(db_column='duration')),
                ('final_date', models.DateTimeField(blank=True, db_column='final_date', null=True)),
                ('start_date', models.DateTimeField(db_column='start_date')),
                ('end_date', models.DateTimeField(db_column='end_date')),
                ('creation_date', models.DateTimeField(db_column='creation_date')),
                ('passcode', models.CharField(db_column='passcode', max_length=5)),
            ],
        ),
    ]
