# Generated by Django 4.2.7 on 2023-11-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='final_date',
            field=models.ForeignKey(blank=True, db_column='final_date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.timeslot'),
        ),
    ]
