# Generated by Django 4.2.7 on 2023-11-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('video_conferencing', models.BooleanField()),
                ('duration', models.PositiveIntegerField()),
                ('date_and_time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
