# Generated by Django 4.2.7 on 2023-11-13 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.CharField(blank=True, db_column='description', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePool',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('voting_start_date', models.DateTimeField()),
                ('voting_deadline', models.DateTimeField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doodle.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='UserFake',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('surname', models.CharField(db_column='surname', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(db_column='id', default=-1, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_column='start_time', null=True)),
                ('end_time', models.DateTimeField(db_column='end_time', null=True)),
                ('schedule_pool', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doodle.schedulepool')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doodle.userfake')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(db_column='id', default=-1, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_column='start_time', default=None)),
                ('preference', models.CharField(db_column='preference', default=None, max_length=100)),
                ('time_slot', models.ForeignKey(db_column='time_slot', default=None, on_delete=django.db.models.deletion.CASCADE, to='doodle.timeslot')),
                ('user', models.ForeignKey(db_column='user', default=None, on_delete=django.db.models.deletion.CASCADE, to='doodle.userfake')),
            ],
            options={
                'unique_together': {('time_slot', 'user')},
            },
        ),
    ]
