# Generated by Django 4.2.7 on 2023-11-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('end_time_range', models.IntegerField()),
                ('start_time_range', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doodle.meeting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doodle.reguser')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('timeslot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doodle.timeslot')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doodle.reguser')),
            ],
        ),
        migrations.AddField(
            model_name='reguser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doodle.user'),
        ),
    ]
