# Generated by Django 4.2.7 on 2023-12-15 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfake',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
    ]
