# Generated by Django 4.2.7 on 2023-11-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfake',
            name='surname2',
            field=models.CharField(db_column='surname2', default=None, max_length=100),
        ),
    ]
