# Generated by Django 4.2.7 on 2023-12-15 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0002_alter_userfake_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfake',
            name='email',
            field=models.EmailField(db_column='email', max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='userfake',
            name='name',
            field=models.CharField(db_column='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='userfake',
            name='surname',
            field=models.CharField(db_column='surname', max_length=20),
        ),
    ]
