# Generated by Django 4.2.7 on 2023-11-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0003_remove_userfake_surname2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='start_time',
        ),
    ]
