# Generated by Django 4.2.7 on 2023-12-15 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0003_alter_userfake_email_alter_userfake_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.IntegerField(db_column='duration', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
