# Generated by Django 4.2.7 on 2023-11-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0004_remove_vote_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='schedule_pool',
        ),
    ]
