# Generated by Django 4.2.7 on 2023-12-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0004_alter_meeting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(db_column='end_time'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(db_column='start_time'),
        ),
    ]
