# Generated by Django 4.2.7 on 2023-11-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0005_remove_timeslot_schedule_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='schedule_pool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doodle.schedulepool'),
        ),
    ]
