# Generated by Django 4.2.7 on 2023-11-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0006_timeslot_schedule_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
