name: Publishing Workflow

on:
    push:
        branches: ["main", "ci_cd_test"]
    
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{github.repository}}

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          
          - name: Login to the Container Registry
            uses: docker/login-action@v3
            with:
              registry: ${{env.REGISTRY}}
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
        
        
          - name: Apply semantic-release tag
            id: semver
            uses: python-semantic-release/python-semantic-release@master
            with:
              github_token: ${{secrets.GITHUB_TOKEN}}
            

          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: .docker/build.DockerFile
              push: true
              tags: ${{steps.semver.outputs.tag}} 
              labels: ${{ steps.meta.outputs.labels }}
