name: Continuous Integration Workflow

on:
    workflow_dispatch:
    pull_request:
        branches: ["group_1", "group_2", "ci_cd_test"]
    push:
      branches: ["ci_cd_test"] 
jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4

            - name: Install React dependencies
              uses: actions/setup-node@v3
              with: 
                cache: 'npm'
                cache-dependency-path: doodle_django/doodle_react/package-lock.json

            - run: npm ci
              working-directory: doodle_django/doodle_react

            - uses: actions/setup-python@v3
            - name: Install Django dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Running tests
              run: python manage.py test doodle.tests
              working-directory: doodle_django