name: Continuous Integration Workflow

on:
    workflow_dispatch:
    pull_request:
        branches: ["group_1", "group_2"]
    push:
        branches: ["group2_cicd"]

defaults:
  run: 
    working-directory: ./doodle_django

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v3


            - uses: actions/checkout@v4
            - run:
                ls -a
            - uses: actions/setup-node@v4
              with:
                node-version: '21.x'
                cache: 'npm'
                cache-dependency-path: '/home/runner/work/doodle-user-friendly/doodle-user-friendly/doodle_django/doodle_react/package-lock.json'
                
            - run: npm ci
              working-directory: ./doodle_react

            - uses: actions/setup-python@v3
            - name: Install Django dependencies
              run: |
                python -m pip install --upgrade pip
                pip install black
                pip install -r requirements.txt
            
            - name: Lint with black
              run: black .
            
            - name: Running tests with pytest
              run: pytest
              working-directory: ./doodle_django
            
            - name: Running tests with django
              run: python manage.py test
              working-directory: ./doodle_django
