name: Continuous Integration Workflow

on:
    workflow_dispatch:
    pull_request:
        branches: ["group_1"]
        
jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v3

            - name: Install React dependencies
              uses: actions/setup-node@v3
              with: 
                cache: 'npm'
                cache-dependency-path: doodle_django/doodle_react/package-lock.json

            - run: npm ci
              working-directory: doodle_django/doodle_react

            - uses: actions/setup-python@v3
            - name: Install Django dependencies
              run: |
                python -m pip install --upgrade pip
                pip install black
                pip install -r requirements.txt
            
            - name: Lint with black
              run: black .
            
            - name: Running tests
              run: pytest
              working-directory: doodle_django